name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
      with:
          submodules: recusive
          path: blender
    - name: Checkout SVN Libraries
      run: |
        svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc15/ ../lib/win64_vc15
    - name: Update
      run: |
        cmd /c make.bat update
    - name: Build
      run: |
        cmd /c make.bat full
        ls
